### ISSUE TITLE
How do i fix error in python import

### ISSUE THREAD

**Issue by jeonhaeng** [Dangku/RPi.GPIO-Amlogic#3]
for bananapi M5

I use official information like this from banana pi web site.

 $ sudo apt-get update
 $ sudo apt-get install build-essential python python-dev python-setuptools git
 $ git clone https://github.com/Dangku/RPi.GPIO-Amlogic.git
 $ cd RPi.GPIO-Amlogic
 $ sudo python setup.py clean --all
 $ sudo python setup.py build install

I can't running GPIO in python error..

import RPi.GPIO
-->
ImportError: /usr/local/lib/python3.9/dist-packages/RPi.GPIO-0.7.1-py3.9-linux-aarch64.egg/RPi/_GPIO.cpython-39-aarch64-linux-gnu.so: undefined symbol: gpio_direction

**Comment by Dangku** [comment]
fixed,
https://github.com/Dangku/RPi.GPIO-Amlogic/commit/a3a314deacf0b8868435226d174f3678b09c7bf7
